# Generated by Django 5.1.5 on 2025-01-29 16:59

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airdrops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reward', models.CharField(max_length=255)),
                ('path_airdrop_img', models.ImageField(blank=True, max_length=255, null=True, upload_to='airdrop_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
            ],
        ),
        migrations.CreateModel(
            name='BannerImagePopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners_pop_ups/', verbose_name='Изображение')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
            ],
        ),
        migrations.CreateModel(
            name='BaseCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=50)),
                ('contract_address', models.CharField(blank=True, max_length=52, null=True)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=35, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=18, max_digits=64, null=True)),
                ('liquidity_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('volume_usd', models.DecimalField(decimal_places=2, max_digits=20)),
                ('volume_btc', models.DecimalField(decimal_places=2, max_digits=20)),
                ('price_change_24h', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price Change 24h')),
                ('path_coin_img', models.CharField(max_length=255)),
                ('path_chain_img', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('pair_url', models.URLField()),
            ],
            options={
                'verbose_name': 'Base Coin',
                'verbose_name_plural': 'Base Coins',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=50)),
                ('contract_address', models.CharField(blank=True, max_length=52, null=True)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=35, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=18, max_digits=64, null=True)),
                ('liquidity_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('volume_usd', models.DecimalField(decimal_places=2, max_digits=20)),
                ('volume_btc', models.DecimalField(decimal_places=2, max_digits=20)),
                ('price_change_24h', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price Change 24h')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('selected_auto_voting', models.BooleanField(default=False)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None, verbose_name='Tags')),
                ('chain', models.CharField(max_length=30)),
                ('votes', models.IntegerField(default=0)),
                ('votes24h', models.IntegerField(default=0)),
                ('market_cap_presale', models.BooleanField(default=False)),
                ('path_coin_img', models.ImageField(max_length=255, upload_to='coin_images/')),
                ('path_chain_img', models.ImageField(max_length=255, upload_to='chain_images/')),
                ('launch_date_str', models.CharField(blank=True, max_length=50, null=True)),
                ('launch_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Coin',
                'verbose_name_plural': 'Coins',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_coins', models.IntegerField(blank=True, null=True)),
                ('count_airdrops', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('per_page', models.PositiveIntegerField(default=10)),
                ('theme_site', models.CharField(default='dark', max_length=10)),
                ('today_hot', models.BooleanField(default=False)),
                ('all_time_best', models.BooleanField(default=True)),
                ('gem_pad', models.BooleanField(default=False)),
                ('new', models.BooleanField(default=False)),
                ('presale', models.BooleanField(default=False)),
                ('doxxed', models.BooleanField(default=False)),
                ('audited', models.BooleanField(default=False)),
                ('item_sub_symbol', models.CharField(max_length=20, null=True)),
                ('head_filter', models.CharField(max_length=30, null=True)),
                ('coins_votes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None, verbose_name='Coins Votes')),
            ],
        ),
        migrations.CreateModel(
            name='PromotedCoins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('coin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promoted', to='app.coin')),
            ],
        ),
        migrations.CreateModel(
            name='ReclamBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('right-banner', 'Top Right Banner'), ('left-banner', 'Top Left Banner'), ('banner_1', 'Banner Bottom 1'), ('banner_2', 'Banner Bottom 2'), ('banner_3', 'Banner Bottom 3'), ('banner_4', 'Banner Bottom 4'), ('banner_5', 'Banner Bottom 5'), ('banner_6', 'Banner Bottom 6')], max_length=20)),
                ('image', models.ImageField(upload_to='banners/')),
                ('link', models.URLField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Reclam Banner',
                'verbose_name_plural': 'Reclam Banners',
                'indexes': [models.Index(fields=['start_time', 'end_time'], name='app_reclamb_start_t_7a93e4_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReclamBannerPopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('rb', 'Right Banner'), ('cb', 'Center Banner'), ('lb', 'Left Banner')], default='rb', max_length=2, verbose_name='Banner position')),
                ('link', models.URLField(blank=True, null=True)),
                ('start_time', models.DateTimeField(verbose_name='Image display start time')),
                ('end_time', models.DateTimeField(verbose_name='Image display end time')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('current_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_banner', to='app.bannerimagepopup', verbose_name='Current Image')),
                ('images', models.ManyToManyField(related_name='banners', to='app.bannerimagepopup', verbose_name='Banner images')),
            ],
            options={
                'verbose_name': 'Reclam Banner PopUp',
                'verbose_name_plural': 'Reclam Banners PopUps',
            },
        ),
    ]
