# Generated by Django 5.1.5 on 2025-01-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecoin',
            name='path_chain_img',
            field=models.ImageField(max_length=255, upload_to='base_chain_images/'),
        ),
        migrations.AlterField(
            model_name='basecoin',
            name='path_coin_img',
            field=models.ImageField(max_length=255, upload_to='base_coin_images/'),
        ),
    ]
