# Generated by Django 5.1.5 on 2025-02-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_basecoin_path_chain_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecoin',
            name='path_chain_img',
            field=models.ImageField(max_length=255, upload_to='chain_images/'),
        ),
    ]
