# Generated by Django 5.1.5 on 2025-02-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_basecoin_slug_coin_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecoin',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coin',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
