# Generated by Django 5.1.5 on 2025-02-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_basecoin_views_coin_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecoin',
            name='price_change_percentage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='price_change_percentage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
