# Generated by Django 5.1.5 on 2025-02-11 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_basecoin_price_change_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=50)),
                ('path_chain_img', models.ImageField(max_length=255, upload_to='chain_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='basecoin',
            name='path_chain_img',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='path_chain_img',
        ),
        migrations.AddField(
            model_name='basecoin',
            name='chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_coin', to='app.chain'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coin', to='app.chain'),
        ),
    ]
