# Generated by Django 5.1.5 on 2025-02-11 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_chain_remove_basecoin_path_chain_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basecoin',
            name='chain',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='chain',
        ),
        migrations.CreateModel(
            name='ContractAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(blank=True, max_length=52, null=True)),
                ('chain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_address', to='app.chain')),
            ],
        ),
        migrations.AlterField(
            model_name='basecoin',
            name='contract_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_coin', to='app.contractaddress'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='contract_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coin', to='app.contractaddress'),
        ),
    ]
