# Generated by Django 5.1.5 on 2025-02-11 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_basecoin_chain_remove_coin_chain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='contract_address',
        ),
        migrations.AddField(
            model_name='basecoin',
            name='name_chain',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='basecoin',
            name='path_chain_img',
            field=models.ImageField(default='', max_length=255, upload_to='chain_images/'),
        ),
        migrations.AddField(
            model_name='basecoin',
            name='symbol_chain',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='contractaddress',
            name='coin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_address', to='app.coin'),
        ),
        migrations.AlterField(
            model_name='basecoin',
            name='contract_address',
            field=models.CharField(blank=True, max_length=52, null=True),
        ),
    ]
