# Generated by Django 5.1.5 on 2025-02-11 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_coin_contract_address_basecoin_name_chain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractaddress',
            name='chain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_address', to='app.chain'),
        ),
        migrations.AlterField(
            model_name='contractaddress',
            name='coin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_address', to='app.coin'),
        ),
    ]
