# Generated by Django 5.1.5 on 2025-02-11 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_contractaddress_chain_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chain',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='contractaddress',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='coin',
            name='launch_date_str',
        ),
    ]
