# Generated by Django 5.1.5 on 2025-02-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_chain_slug_alter_chain_symbol_alter_coin_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecoin',
            name='pair_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basecoin',
            name='path_coin_img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='base_coin_images/'),
        ),
        migrations.AlterField(
            model_name='basecoin',
            name='price_change_24h',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price Change 24h'),
        ),
        migrations.AlterField(
            model_name='basecoin',
            name='volume_btc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='basecoin',
            name='volume_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='chain',
            name='path_chain_img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='chain_images/'),
        ),
        migrations.AlterField(
            model_name='chain',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coin',
            name='path_coin_img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='coin_images/'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='price_change_24h',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price Change 24h'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='volume_btc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='volume_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
