# Generated by Django 5.1.5 on 2025-02-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_basecoin_pair_url_alter_basecoin_path_coin_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractaddress',
            name='basic',
            field=models.BooleanField(default=False),
        ),
    ]
