# Generated by Django 5.1.5 on 2025-02-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_contractaddress_basic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='coin',
            name='tags',
        ),
        migrations.AddField(
            model_name='coin',
            name='labels',
            field=models.ManyToManyField(related_name='coin', to='app.label'),
        ),
    ]
