# Generated by Django 5.1.5 on 2025-02-12 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_label_remove_coin_tags_coin_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_company', models.CharField(blank=True, max_length=255, null=True)),
                ('audit_link', models.URLField(blank=True, null=True)),
                ('doxxed', models.URLField(blank=True, null=True)),
                ('coin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audit_info', to='app.coin')),
            ],
        ),
        migrations.CreateModel(
            name='CoinDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_0', models.TextField(blank=True, null=True)),
                ('desc_1', models.TextField(blank=True, null=True)),
                ('desc_2', models.TextField(blank=True, null=True)),
                ('desc_3', models.TextField(blank=True, null=True)),
                ('desc_4', models.TextField(blank=True, null=True)),
                ('desc_5', models.TextField(blank=True, null=True)),
                ('coin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='app.coin')),
            ],
        ),
        migrations.CreateModel(
            name='CoinSocials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.URLField(blank=True, null=True)),
                ('reddit', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('gecko', models.URLField(blank=True, null=True)),
                ('discord', models.URLField(blank=True, null=True)),
                ('market', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('tiktok', models.URLField(blank=True, null=True)),
                ('medium', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('coin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='app.coin')),
            ],
        ),
        migrations.CreateModel(
            name='PresaleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presale', models.BooleanField(default=False)),
                ('softcap', models.CharField(blank=True, max_length=50, null=True)),
                ('presale_link', models.URLField(blank=True, null=True)),
                ('hardcap', models.CharField(blank=True, max_length=50, null=True)),
                ('presale_date', models.DateField(blank=True, null=True)),
                ('whitelist', models.BooleanField(default=False)),
                ('coin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presale_info', to='app.coin')),
            ],
        ),
        migrations.CreateModel(
            name='TaxInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_tax', models.IntegerField(blank=True, default=0, null=True)),
                ('buy_tax', models.IntegerField(blank=True, default=0, null=True)),
                ('slippage', models.IntegerField(blank=True, default=0, null=True)),
                ('coin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_info', to='app.coin')),
            ],
        ),
    ]
