# Generated by Django 5.1.5 on 2025-02-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_coin_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecoin',
            name='format_price',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='format_price',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
