# Generated by Django 5.1.5 on 2025-02-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_basecoin_format_price_coin_format_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecoin',
            name='name_chain',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='basecoin',
            name='symbol_chain',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
