# Generated by Django 5.1.5 on 2025-02-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_basecoin_name_chain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecoin',
            name='pair_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
