# Generated by Django 5.1.5 on 2025-02-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_basecoin_pair_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecoin',
            name='path_chain_img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='chain_images/'),
        ),
    ]
