# Generated by Django 5.1.5 on 2025-02-16 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_basecoin_path_chain_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PromotedCoins',
            new_name='PromotedCoin',
        ),
        migrations.AlterModelOptions(
            name='contractaddress',
            options={'ordering': ['id'], 'verbose_name': 'Contract Address', 'verbose_name_plural': 'Contract Addresses'},
        ),
        migrations.AlterModelOptions(
            name='promotedcoin',
            options={'ordering': ['id'], 'verbose_name': 'Promoted Coin', 'verbose_name_plural': 'Promoted Coins'},
        ),
    ]
