# Generated by Django 5.1.5 on 2025-02-16 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_rename_promotedcoins_promotedcoin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotedcoin',
            options={'ordering': ['id'], 'verbose_name': 'Promoted Coin', 'verbose_name_plural': 'Promoted Coin'},
        ),
    ]
