# Generated by Django 5.1.5 on 2025-02-16 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_promotedcoin_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airdrops',
            options={'ordering': ['id'], 'verbose_name': 'Airdrops', 'verbose_name_plural': 'Airdrops'},
        ),
    ]
