# Generated by Django 5.1.5 on 2025-02-17 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_airdrops_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coinsocials',
            old_name='discord',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='coinsocials',
            name='gecko',
        ),
        migrations.RemoveField(
            model_name='coinsocials',
            name='github',
        ),
        migrations.RemoveField(
            model_name='coinsocials',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='coinsocials',
            name='market',
        ),
        migrations.RemoveField(
            model_name='coinsocials',
            name='medium',
        ),
        migrations.RemoveField(
            model_name='coinsocials',
            name='reddit',
        ),
        migrations.RemoveField(
            model_name='coinsocials',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='coinsocials',
            name='tiktok',
        ),
        migrations.RemoveField(
            model_name='coinsocials',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='coinsocials',
            name='website',
        ),
        migrations.RemoveField(
            model_name='coinsocials',
            name='youtube',
        ),
        migrations.AddField(
            model_name='coinsocials',
            name='icon',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='social_icons/'),
        ),
        migrations.AddField(
            model_name='coinsocials',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coinsocials',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coinsocials',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='app.coin'),
        ),
    ]
