# Generated by Django 5.1.5 on 2025-02-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_rename_discord_coinsocials_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chain',
            name='path_chain_img',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='chain_images/'),
        ),
    ]
