# Generated by Django 5.1.5 on 2025-02-18 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_chain_path_chain_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('name', models.CharField(help_text='Название маркета', max_length=100)),
                ('image', models.FileField(blank=True, max_length=255, null=True, upload_to='market_images/')),
                ('description', models.TextField(blank=True, help_text='Краткое описание маркета', null=True)),
                ('chain', models.ForeignKey(help_text='Чейн, к которому относится этот маркет', on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='app.chain')),
            ],
            options={
                'verbose_name': 'Market',
                'verbose_name_plural': 'Markets',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MarketAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_template', models.URLField(help_text='URL маркета с шаблоном для замены {contract_address}')),
                ('market', models.ForeignKey(help_text='Маркет, к которому относится этот адрес', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='app.market')),
            ],
            options={
                'verbose_name': 'Market Address',
                'verbose_name_plural': 'Market Addresses',
                'ordering': ['id'],
            },
        ),
    ]
