# Generated by Django 5.1.5 on 2025-02-18 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_remove_marketaddress_market_chainmarket_marketinfo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chainmarket',
            options={'ordering': ['id'], 'verbose_name': 'Chain Market', 'verbose_name_plural': 'Chain Markets'},
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_market', models.CharField(blank=True, max_length=50, null=True)),
                ('url_template', models.URLField(help_text='URL маркета с шаблоном для замены {contract_address}')),
                ('image', models.FileField(blank=True, max_length=255, null=True, upload_to='market_images/')),
                ('description', models.TextField(blank=True, help_text='Краткое описание маркета', null=True)),
                ('market', models.ForeignKey(help_text='Маркет, к которому относится этот адрес', on_delete=django.db.models.deletion.CASCADE, related_name='market', to='app.chainmarket')),
            ],
            options={
                'verbose_name': 'Market',
                'verbose_name_plural': 'Markets',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='MarketInfo',
        ),
    ]
