# Generated by Django 5.1.5 on 2025-02-19 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_chainmarket_options_market_delete_marketinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractaddress',
            name='coin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_address', to='app.coin'),
        ),
    ]
